### ISSUE TITLE
Cannot load pass module (locale error)

### ISSUE THREAD

**Issue by 0xdc** [Pext/pext_module_pass#6]
Trying to load the pass module. On clicking "OK", nothing in the pext window changes and this message is printed into the terminal:

```
WARN: Module pass uses old process_response signature and will not be able to receive an identifier if requested
WARN: Module pass caused exception 'Module' object has no attribute 'observer' on unload
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/pext/__main__.py", line 1087, in unload_module
    window.tab_bindings[tab_id]['module'].stop()
  File "/home/me/.config/pext/modules/pext_module_pass/__init__.py", line 253, in stop
    self.observer.stop()
AttributeError: 'Module' object has no attribute 'observer'
file:///usr/lib64/python3.5/site-packages/pext/qml/ModuleData.qml:27: TypeError: Cannot read property of null
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/pext/__main__.py", line 1377, in run
    threading.Thread.run(self)
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/.config/pext/modules/pext_module_pass/__init__.py", line 39, in init
    lang = gettext.translation('pext_module_pass', localedir=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'locale'), languages=[settings['_locale']])
  File "/usr/lib64/python3.5/gettext.py", line 510, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib64/python3.5/gettext.py", line 482, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib64/python3.5/gettext.py", line 206, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib64/python3.5/locale.py", line 392, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Tested with LC_ALL=en_GB.utf8 and LC_ALL=nl_NL.utf8, both have the same results.

Running on Gentoo with `PYTHON_SINGLE_TARGET="python3_5" PYTHON_TARGETS="python2_7 python3_5 python3_6"`:
```
dev-python/dulwich-0.18.5::gentoo
dev-python/pip-9.0.1-r1::gentoo
dev-python/PyQt5-5.7.1::gentoo
dev-qt/qtquickcontrols-5.7.1:5/5.7::gentoo
app-admin/pass-1.7.1::gentoo
```

**Comment by TheLastProject** [comment]
Thanks for the report!

I believe this was fixed in the development version of Pext. Could you try it with the latest development version of https://github.com/Pext/Pext?

**Comment by 0xdc** [comment]
Hi @TheLastProject,

I do not get the error message when using pext git master, and it appears to work correctly.

I'll close this bug since https://github.com/Pext/Pext/issues/96 is tracking version bumping.

**Comment by TheLastProject** [comment]
Thank you for confirming :)
