### ISSUE TITLE
could not find .gpg-id file when entering a wrong SSH key password

### ISSUE THREAD

**Issue by TheLastProject** [Pext/pext_module_pass#68]
Module version gd9814a4
Pext v0.30-20-g0856c9d on linux

```
Traceback (most recent call last):
  File "pext/__main__.py", line 1794, in run
    threading.Thread.run(self)
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sylvia/.config/pext/modules/pext_module_pass/__init__.py", line 63, in init
    self.password_store = pypass.PasswordStore(self.data_location)
  File "/home/sylvia/.local/lib/python3.7/site-packages/pypass/passwordstore.py", line 64, in __init__
    raise Exception("could not find .gpg-id file")
Exception: could not find .gpg-id file
```

Like, whaaaat?

**Comment by TheLastProject** [comment]
Can't reliably reproduce, very weird.
