### ISSUE TITLE
GitLab OTP key breaks password decryption

### ISSUE THREAD

**Issue by TheLastProject** [Pext/pext_module_pass#69]
Copying GitLab's key as-in without removing spaces:

```
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sylviavanos/.config/pext/modules/pext_module_pass/__init__.py", line 499, in _display_results
    otp_code = otp.now()
  File "/usr/local/lib/python3.7/site-packages/pyotp/totp.py", line 44, in now
    return self.generate_otp(self.timecode(datetime.datetime.now()))
  File "/usr/local/lib/python3.7/site-packages/pyotp/otp.py", line 45, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
  File "/usr/local/lib/python3.7/site-packages/pyotp/otp.py", line 62, in byte_secret
    return base64.b32decode(self.secret, casefold=True)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
```

Also, when scanning the screen, the code doesn't seem to get added at all?!

**Comment by TheLastProject** [comment]
Fixed in 5140092285b7571138fc3b0c71040a4fb1832ee2 and 8e5378f048104327bd3c1e139b1c5ffea9945650.
