### ISSUE TITLE
Editing an entry through the context menu twice in a row causes exception

### ISSUE THREAD

**Issue by TheLastProject** [Pext/pext_module_pass#8]
```
Traceback (most recent call last):
  File "pext/__main__.py", line 442, in <lambda>
    lambda userinput: tab['vm'].module.process_response(userinput))
  File "/home/sylvia/.config/pext/modules/pext_module_pass/__init__.py", line 255, in process_response                                                                     
    self._run_command([self.proc['command']] + response.split(" "))
KeyError: 'command'
```

**Comment by TheLastProject** [comment]
I'm honestly still not sure why the pass module gets EOF multiple times after the first edit, but f3c8fbb5631fbbd26c75eb381c84910c30e67d68 fixes this.
